# Generated by Django 4.2.2 on 2023-06-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='titre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='Titre',
            field=models.CharField(help_text='Cellule Informatique , etc', max_length=200),
        ),
        migrations.AlterField(
            model_name='grade',
            name='niveau',
            field=models.PositiveIntegerField(help_text='Exemple de niveau 1,2,3....'),
        ),
    ]
