# Generated by Django 4.2.2 on 2023-06-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_responsable_titre_alter_grade_titre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='user_grade'),
        ),
    ]
