# Generated by Django 4.2.2 on 2023-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_content_article_contetu_article_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Banniere',
            field=models.ImageField(default='  ', upload_to='Banieres', verbose_name='Banière'),
            preserve_default=False,
        ),
    ]
